Move script to bin

diff --git a/ingestion-beam/bin/run-pioneer-benchmark b/ingestion-beam/bin/run-pioneer-benchmark
--- a/ingestion-beam/bin/run-pioneer-benchmark
+++ b/ingestion-beam/bin/run-pioneer-benchmark
@@ -1,4 +1,12 @@
 #!/bin/bash
+# Runs a benchmark that can be used to quantify the overhead of the
+# DecryptPioneerPayloads step. A document sample of ingested data is encrypted
+# using JOSE and is run through the Pioneer-enabled decoder. This is compared
+# against the plaintext data.
+#
+# Initial findings show that for every 1 minute spent on ParsePayload, there are
+# 3 minutes spend on DecryptPioneerPayloads. Peak throughput in ParsePayload
+# goes from 3360 elements/sec to 2466 elements/sec when adding encryption.
 
 set -ex
 
@@ -7,8 +15,14 @@ reset=${RESET:-false}
 project=$(gcloud config get-value project)
 bucket="gs://${BUCKET:-$project}"
 prefix="ingestion-beam-benchmark"
-staging=benchmark_staging
+staging="benchmark_staging"
 
+cd "$(dirname "$0")/.."
+
+if [[ ! -f document_sample.ndjson ]]; then
+    echo "missing document_sample.ndjson, run download-document-sample"
+    exit 1
+fi
 
 if [[ ! -f pioneer_benchmark_data.ndjson ]] || ${reset}; then
     # generate the data using the document sample, this may take a while depending on your machine
@@ -26,6 +40,7 @@ if [[ ! -d $staging ]]; then
     mkdir -p $plaintext
     mkdir -p $ciphertext
     mkdir -p $metadata
+    # shuffle to avoid data skew, and to prepare for file splitting if necessary
     shuf document_sample.ndjson > $plaintext/part-0.ndjson
     shuf pioneer_benchmark_data.ndjson > $ciphertext/part-0.ndjson
     cp pioneer_benchmark_key.json $staging/metadata/key.json
@@ -36,6 +51,8 @@ if [[ ! -d $staging ]]; then
     cp cities15000.txt $metadata
     cp GeoLite2-City.mmdb $metadata
 fi
+
+# this can take a while, depending on your upload speed (~1 GB of data)
 gsutil -m rsync -R -d $staging/ "$bucket/$prefix/"
 
 # plaintext
